services: 
  php: 
    build: 
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    networks: 
      - nginx-php
      - php-mysql
    volumes: 
      - ./:/var/www/html
    depends_on: 
      - mysql

  nginx: 
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    networks:
      - nginx-php
    ports: 
      - "80:80"
    volumes: 
      - ./:/var/www/html
    depends_on:
      - php
  
  mysql: 
    image: mysql:latest
    container_name: mysql
    networks:
      - php-mysql
    volumes: 
      - mysqlvolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbcyber
      - MYSQL_USER=dockersymfony
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"

  myadmin: 
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    networks: 
      - php-mysql
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    ports: 
      - "8080:80"
    platform: linux/amd64

networks: 
  nginx-php:
  php-mysql:

volumes: 
  mysqlvolume:

