name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    
    # - name: Copy .env.test.local
    # run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      
    # Cache for composer dependencies
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Configure Git
    - name: Setup Git config
      run: |
        git config --global user.email "actions@github.fr"
        git config --global user.name "actions"
        
    # Install dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Validate composer.json
      run: composer validate --strict

    # Linters
    - name: Run PHP_CodeSniffer
      run: vendor/bin/phpcs

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse

    - name: Run TwigCS
      run: vendor/bin/twigcs templates/

    # Run migrations
    #- name: Run Doctrine Migrations
     # env:
        #DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #run: |
        #php bin/console doctrine:migrations:status
        #php bin/console doctrine:migrations:migrate --no-interaction

  CD:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: CI
    
    steps:
      - uses: actions/checkout@v3
      
      # Install Railway CLI
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
  
      # Check Railway CLI Version
      - name: Check Railway CLI version
        run: railway --version
  
      # Deploy to Railway
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service 577a186d-9326-445d-926f-a9b07040d070
